### ISSUE TITLE
Some datas obtained from the reference are not the same as the data on github

### ISSUE THREAD

**Issue by duxiaoxian** [PhasesResearchLab/ESPEI-datasets#13]
I found that the input data for Ni3Al on github is different from the reference of "Shunli DFT calculations (2010)". Is the reference "First-principles thermodynamics from phonon and Debye model: Application to Ni and Ni3Al"? The HM, SM, CPM data obtained from Fig7 and 8 are not the same as the data on github. For example, the HM value at 1615K, github is 39428.25, while in the literature is 157430.
What caused it? Do we need a numerical conversion?

**Comment by duxiaoxian** [comment]
ESPEI-datasets/AL-NI/input-json/FCC_L12/AL-NI-HM-FCC_L12-Shunli DFT calculations (2010).json

**Comment by bocklund** [comment]
If you look in the figure captions, e.g. in Figure 7, the Ni3Al data is reported with units J/mol-formula (per unit cell of Ni3Al, with 4 atoms). ESPEI single phase data always must be J/mole-atom, so the Ni3Al dataset is 1/4 the values in the figures.

**Comment by duxiaoxian** [comment]
I got it. I am all gratitude.
