### ISSUE TITLE
Work-stealing problem

### ISSUE THREAD

**Issue by June813** [PhasesResearchLab/ESPEI-datasets#15]
Hi Richard,
I'm running the CU-MG example and have an issue about the work-stealing setting. After I finished the installation of Espei, I have already set the work-stealing value as false.  I successfully generated the Cu-Mg_dft.tdb and no error was reported. When I move on to the MCMC optimization and try to generate the Cu-Mg_mcmc.tdb following the instruction, the value error is reported as "work-stealing is on in dask". But I checked the distributed.YAML,  work-stealing status is still false. I don't know how to fix this, hope to hear from you soon.
![work-stealing](https://user-images.githubusercontent.com/53927918/64424221-75a55a80-d076-11e9-8ed8-aeb0b0294991.JPG)
![value error](https://user-images.githubusercontent.com/53927918/64424226-79d17800-d076-11e9-8459-4144f8e57e4b.JPG)

**Comment by bocklund** [comment]
Hey, @June813, in YAML files, any text after a `#` is a comment, so this file is actually just accepting the default value in dask, which is to set work stealing. 

To change this file, delete the comment and first space so at least the following lines are un-commented:

```yaml
distributed:
  version: 2
  scheduler:
    work-stealing: False
```

**Comment by June813** [comment]
> Hey, @June813, in YAML files, any text after a `#` is a comment, so this file is actually just accepting the default value in dask, which is to set work stealing.
> 
> To change this file, delete the comment and first space so at least the following lines are un-commented:
> 
> ```yaml
> distributed:
>   version: 2
>   scheduler:
>     work-stealing: False
> ```

Thank you! It works!

**Comment by bocklund** [comment]
Great, glad it works for you! FYI our Gitter chat, https://gitter.im/PhasesResearchLab/ESPEI, is another good place for these kind of questions.
