### ISSUE TITLE
Always get error in dataset checking of Cu-Mg activity

### ISSUE THREAD

**Issue by Pure-Alex** [PhasesResearchLab/ESPEI-datasets#18]
I'm trying to reproduce the Cu-Mg phase diagram but always get the following error message:

Dataset Error in input-data\activity\CU-MG-ACR_MG-LIQUID-garg1973thermodynamic.json: Shape of conditions (P, T, configs): (1, 1, 1) does not match the shape of the values (1, 1, 10).
![image](https://user-images.githubusercontent.com/19656617/80443011-35803a00-88dc-11ea-81d3-d61756dd0001.png)

I tried it again with other systems but always found issues for activity datasets.

**Comment by bocklund** [comment]
Hi @Pure-Alex, the `solver` key in that dataset is not required and ESPEI has recently become more strict on not allowing this key in the equilibrium thermochemical datasets. It's deleted now.

I just made a commit with this fix to the dataset that passes the dataset checker on the most recent ESPEI. You can update with `git pull` from the `ESPEI-datasets` directory that you cloned to (or just redownload the archive if you got the datasets directory that way).

**Comment by bocklund** [comment]
Fixed by #22
